// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfYq7Z-S3UBzR6-DzWtooMJJoZpjG_G-A',
    appId: '1:950423177628:web:915529a7a480b3ffe36059',
    messagingSenderId: '950423177628',
    projectId: 'flutter-game-d38ee',
    authDomain: 'flutter-game-d38ee.firebaseapp.com',
    storageBucket: 'flutter-game-d38ee.firebasestorage.app',
    measurementId: 'G-818SJEP6N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-62XusmkihM_c_kJ7icYEKokY9EYQbE',
    appId: '1:950423177628:android:30f8722981ebe46de36059',
    messagingSenderId: '950423177628',
    projectId: 'flutter-game-d38ee',
    storageBucket: 'flutter-game-d38ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_GGi8dhQNefA7zlW4FnAqktSAcMPEqw8',
    appId: '1:950423177628:ios:5c130fc25ac58fc1e36059',
    messagingSenderId: '950423177628',
    projectId: 'flutter-game-d38ee',
    storageBucket: 'flutter-game-d38ee.firebasestorage.app',
    iosBundleId: 'com.mahmoudalaa.flutterGameGdg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_GGi8dhQNefA7zlW4FnAqktSAcMPEqw8',
    appId: '1:950423177628:ios:5c130fc25ac58fc1e36059',
    messagingSenderId: '950423177628',
    projectId: 'flutter-game-d38ee',
    storageBucket: 'flutter-game-d38ee.firebasestorage.app',
    iosBundleId: 'com.mahmoudalaa.flutterGameGdg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfYq7Z-S3UBzR6-DzWtooMJJoZpjG_G-A',
    appId: '1:950423177628:web:441358520aa3544fe36059',
    messagingSenderId: '950423177628',
    projectId: 'flutter-game-d38ee',
    authDomain: 'flutter-game-d38ee.firebaseapp.com',
    storageBucket: 'flutter-game-d38ee.firebasestorage.app',
    measurementId: 'G-2CE5RSSWMZ',
  );
}
